// <auto-generated />
using System;
using FormCollector.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormCollector.Infrastructure.Migrations
{
    [DbContext(typeof(FormCollectorDbContext))]
    partial class FormCollectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormCollector.Domain.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on_utc");

                    b.HasKey("Id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("FormCollector.Domain.Submission", b =>
                {
                    b.OwnsOne("FormCollector.Domain.FormData", "FormData", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("form_id");

                            b1.Property<string>("Name")
                                .HasColumnType("text")
                                .HasColumnName("form_name");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.OwnsOne("FormCollector.Domain.Payload", "Payload", b1 =>
                        {
                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Flattened")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("flattened_text");

                            b1.Property<string>("Json")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("json_payload");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("submissions");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.Navigation("FormData")
                        .IsRequired();

                    b.Navigation("Payload")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
